site_name: Notas Musicais
repo_url: https://github.com/unclesummer/notas-musicais
repo_name: unclesummer/notas-musicais


theme:
  name: material
  language: pt-BR



watch:
  - notas_musicais

plugins: 
- mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais]