name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1' 

      - name: Instalar Poetry
        run: pip install poetry